// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: message/arrived.proto

package message

import (
	types "github.com/atmatm9182/silly-hippos/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Arrived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hippo *types.Hippo `protobuf:"bytes,1,opt,name=hippo,proto3" json:"hippo,omitempty"`
}

func (x *Arrived) Reset() {
	*x = Arrived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_arrived_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arrived) ProtoMessage() {}

func (x *Arrived) ProtoReflect() protoreflect.Message {
	mi := &file_message_arrived_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arrived.ProtoReflect.Descriptor instead.
func (*Arrived) Descriptor() ([]byte, []int) {
	return file_message_arrived_proto_rawDescGZIP(), []int{0}
}

func (x *Arrived) GetHippo() *types.Hippo {
	if x != nil {
		return x.Hippo
	}
	return nil
}

var File_message_arrived_proto protoreflect.FileDescriptor

var file_message_arrived_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x68, 0x69, 0x70, 0x70, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x07, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x22,
	0x0a, 0x05, 0x68, 0x69, 0x70, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x69, 0x70, 0x70, 0x6f, 0x52, 0x05, 0x68, 0x69, 0x70,
	0x70, 0x6f, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x74, 0x6d, 0x61, 0x74, 0x6d, 0x39, 0x31, 0x38, 0x32, 0x2f, 0x73, 0x69, 0x6c, 0x6c,
	0x79, 0x2d, 0x68, 0x69, 0x70, 0x70, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_arrived_proto_rawDescOnce sync.Once
	file_message_arrived_proto_rawDescData = file_message_arrived_proto_rawDesc
)

func file_message_arrived_proto_rawDescGZIP() []byte {
	file_message_arrived_proto_rawDescOnce.Do(func() {
		file_message_arrived_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_arrived_proto_rawDescData)
	})
	return file_message_arrived_proto_rawDescData
}

var file_message_arrived_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_arrived_proto_goTypes = []any{
	(*Arrived)(nil),     // 0: message.Arrived
	(*types.Hippo)(nil), // 1: types.Hippo
}
var file_message_arrived_proto_depIdxs = []int32{
	1, // 0: message.Arrived.hippo:type_name -> types.Hippo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_arrived_proto_init() }
func file_message_arrived_proto_init() {
	if File_message_arrived_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_arrived_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Arrived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_arrived_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_arrived_proto_goTypes,
		DependencyIndexes: file_message_arrived_proto_depIdxs,
		MessageInfos:      file_message_arrived_proto_msgTypes,
	}.Build()
	File_message_arrived_proto = out.File
	file_message_arrived_proto_rawDesc = nil
	file_message_arrived_proto_goTypes = nil
	file_message_arrived_proto_depIdxs = nil
}
