// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: message/moved.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveDirection int32

const (
	MoveDirection_UP    MoveDirection = 0
	MoveDirection_DOWN  MoveDirection = 1
	MoveDirection_LEFT  MoveDirection = 2
	MoveDirection_RIGHT MoveDirection = 3
)

// Enum value maps for MoveDirection.
var (
	MoveDirection_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	MoveDirection_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x MoveDirection) Enum() *MoveDirection {
	p := new(MoveDirection)
	*p = x
	return p
}

func (x MoveDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_message_moved_proto_enumTypes[0].Descriptor()
}

func (MoveDirection) Type() protoreflect.EnumType {
	return &file_message_moved_proto_enumTypes[0]
}

func (x MoveDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveDirection.Descriptor instead.
func (MoveDirection) EnumDescriptor() ([]byte, []int) {
	return file_message_moved_proto_rawDescGZIP(), []int{0}
}

type Moved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Where MoveDirection `protobuf:"varint,1,opt,name=where,proto3,enum=message.MoveDirection" json:"where,omitempty"`
}

func (x *Moved) Reset() {
	*x = Moved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_moved_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Moved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moved) ProtoMessage() {}

func (x *Moved) ProtoReflect() protoreflect.Message {
	mi := &file_message_moved_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moved.ProtoReflect.Descriptor instead.
func (*Moved) Descriptor() ([]byte, []int) {
	return file_message_moved_proto_rawDescGZIP(), []int{0}
}

func (x *Moved) GetWhere() MoveDirection {
	if x != nil {
		return x.Where
	}
	return MoveDirection_UP
}

var File_message_moved_proto protoreflect.FileDescriptor

var file_message_moved_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35,
	0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05,
	0x77, 0x68, 0x65, 0x72, 0x65, 0x2a, 0x36, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x03, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x74, 0x6d, 0x61,
	0x74, 0x6d, 0x39, 0x31, 0x38, 0x32, 0x2f, 0x73, 0x69, 0x6c, 0x6c, 0x79, 0x2d, 0x68, 0x69, 0x70,
	0x70, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_moved_proto_rawDescOnce sync.Once
	file_message_moved_proto_rawDescData = file_message_moved_proto_rawDesc
)

func file_message_moved_proto_rawDescGZIP() []byte {
	file_message_moved_proto_rawDescOnce.Do(func() {
		file_message_moved_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_moved_proto_rawDescData)
	})
	return file_message_moved_proto_rawDescData
}

var file_message_moved_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_moved_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_moved_proto_goTypes = []any{
	(MoveDirection)(0), // 0: message.MoveDirection
	(*Moved)(nil),      // 1: message.Moved
}
var file_message_moved_proto_depIdxs = []int32{
	0, // 0: message.Moved.where:type_name -> message.MoveDirection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_moved_proto_init() }
func file_message_moved_proto_init() {
	if File_message_moved_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_moved_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Moved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_moved_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_moved_proto_goTypes,
		DependencyIndexes: file_message_moved_proto_depIdxs,
		EnumInfos:         file_message_moved_proto_enumTypes,
		MessageInfos:      file_message_moved_proto_msgTypes,
	}.Build()
	File_message_moved_proto = out.File
	file_message_moved_proto_rawDesc = nil
	file_message_moved_proto_goTypes = nil
	file_message_moved_proto_depIdxs = nil
}
