// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: types/tile-type.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TileType int32

const (
	TileType_GRASS TileType = 0
	TileType_PLAIN TileType = 1
	TileType_DIRT  TileType = 2
)

// Enum value maps for TileType.
var (
	TileType_name = map[int32]string{
		0: "GRASS",
		1: "PLAIN",
		2: "DIRT",
	}
	TileType_value = map[string]int32{
		"GRASS": 0,
		"PLAIN": 1,
		"DIRT":  2,
	}
)

func (x TileType) Enum() *TileType {
	p := new(TileType)
	*p = x
	return p
}

func (x TileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TileType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_tile_type_proto_enumTypes[0].Descriptor()
}

func (TileType) Type() protoreflect.EnumType {
	return &file_types_tile_type_proto_enumTypes[0]
}

func (x TileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TileType.Descriptor instead.
func (TileType) EnumDescriptor() ([]byte, []int) {
	return file_types_tile_type_proto_rawDescGZIP(), []int{0}
}

var File_types_tile_type_proto protoreflect.FileDescriptor

var file_types_tile_type_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x69, 0x6c, 0x65, 0x2d, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x2a,
	0x0a, 0x08, 0x54, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52,
	0x41, 0x53, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x49, 0x52, 0x54, 0x10, 0x02, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x74, 0x6d, 0x61, 0x74, 0x6d, 0x39,
	0x31, 0x38, 0x32, 0x2f, 0x73, 0x69, 0x6c, 0x6c, 0x79, 0x2d, 0x68, 0x69, 0x70, 0x70, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_tile_type_proto_rawDescOnce sync.Once
	file_types_tile_type_proto_rawDescData = file_types_tile_type_proto_rawDesc
)

func file_types_tile_type_proto_rawDescGZIP() []byte {
	file_types_tile_type_proto_rawDescOnce.Do(func() {
		file_types_tile_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_tile_type_proto_rawDescData)
	})
	return file_types_tile_type_proto_rawDescData
}

var file_types_tile_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_tile_type_proto_goTypes = []any{
	(TileType)(0), // 0: types.TileType
}
var file_types_tile_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_tile_type_proto_init() }
func file_types_tile_type_proto_init() {
	if File_types_tile_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_tile_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_tile_type_proto_goTypes,
		DependencyIndexes: file_types_tile_type_proto_depIdxs,
		EnumInfos:         file_types_tile_type_proto_enumTypes,
	}.Build()
	File_types_tile_type_proto = out.File
	file_types_tile_type_proto_rawDesc = nil
	file_types_tile_type_proto_goTypes = nil
	file_types_tile_type_proto_depIdxs = nil
}
